name: Backup Resources

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

permissions:
  contents: write   # Add this permission

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Add token for authentication

      - name: Create backup
        run: |
          mkdir -p backups
          cp resources.json "backups/resources_$(date +%Y%m%d).json"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add backups/
          git commit -m "📦 Backup: $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push

      - name: Cleanup old backups
        run: |
          cd backups
          ls -t | tail -n +8 | xargs rm -f || true  # Keep last 7 backups